### ISSUE TITLE
Build issue in Android Studio

### ISSUE THREAD

**Issue by hardikbhalodi** [jruesga/android_external_libtruezip#1]
Hello i am aware with original TRUE ZIP library for JAVA . i just try to build a project with android using this lib but not working and getting below errors.

de/schlichtherle/truezip/socket/IOPool.java
Error:(34, 25) error: cannot find symbol class Releasable
where E is a type-variable:
E declared in interface IOPool

/de/schlichtherle/truezip/key/PromptingKeyProvider.java
Error:(156, 21) error: non-static class PromptingKeyProvider.BaseController cannot be referenced from a static context
Error:(177, 25) error: non-static class PromptingKeyProvider.BaseController cannot be referenced from a static context
Error:(207, 21) error: non-static class PromptingKeyProvider.BaseController cannot be referenced from a static context

**Comment by jruesga** [comment]
It builds correctly with a simple gradle

```
apply plugin: 'java'

defaultTasks 'build'

sourceCompatibility = JavaVersion.VERSION_1_6
targetCompatibility = JavaVersion.VERSION_1_6

sourceSets {
    main {
        java {
            srcDir 'src/'
        }
    }
}
```

I pushed it into the main branch.

If you want to use inside Android Studio with other app, just create a new module with this gradle script, configure your settings.gradle file and link as project dependency from your Android app.

**Comment by hardikbhalodi** [comment]
Hello,

Thank you, now, it's successfully compiled.

now i made following config for true zip and creating a zip archive with
directory contain text file.

@Override
public void onCreate() {
    super.onCreate();
    TConfig config = TConfig.get();
    // Configure custom application file format.
    config.setArchiveDetector(new TArchiveDetector(
            TArchiveDetector.NULL,
            "zip", new ZipDriver(IOPoolLocator.SINGLETON)));
    // Set FsOutputOption.GROW for appending-to rather than reassembling
    // existing archive files.
    config.setOutputPreferences(
            config.getOutputPreferences().set(FsOutputOption.GROW));

```
File entry = new TFile(Environment.getExternalStorageDirectory() +
```

"/apv.zip/dir/HelloWorld.txt");

AppLog.log(Const.TAG,entry.getAbsolutePath());
if (entry.exists())
    return;
Writer writer = null;
try {
    writer = new TFileWriter(entry);
    writer.write("Hello world!\n");
    writer.close();
} catch (IOException e) {
    e.printStackTrace();
}

}

above code throwing below exception.

FATAL EXCEPTION: main

 java.util.ServiceConfigurationError: file (Unknown file system scheme! May
be the class path doesn't contain the respective driver module or it isn't
set up correctly?)
                                                                     at
de.schlichtherle.truezip.fs.FsAbstractCompositeDriver.newController(FsAbstractCompositeDriver.java:31)
                                                                     at
de.schlichtherle.truezip.fs.FsDefaultManager.getController0(FsDefaultManager.java:93)
                                                                     at
de.schlichtherle.truezip.fs.FsDefaultManager.getController(FsDefaultManager.java:76)
                                                                     at
de.schlichtherle.truezip.file.TBIO.getOutputSocket(TBIO.java:308)
                                                                     at
de.schlichtherle.truezip.file.TFileOutputStream.newOutputStream(TFileOutputStream.java:127)
                                                                     at
de.schlichtherle.truezip.file.TFileOutputStream.<init>(TFileOutputStream.java:107)
                                                                     at
de.schlichtherle.truezip.file.TFileWriter.<init>(TFileWriter.java:32)
                                                                     at
com.example.apv.HomeActivity.createArchive(HomeActivity.java:107)
                                                                     at
com.example.apv.HomeActivity.onCreate(HomeActivity.java:71)
                                                                     at
android.app.Activity.performCreate(Activity.java:5133)
                                                                     at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                     at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2230)
                                                                     at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
                                                                     at
android.app.ActivityThread.access$600(ActivityThread.java:150)
                                                                     at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
                                                                     at
android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at
android.os.Looper.loop(Looper.java:213)
                                                                     at
android.app.ActivityThread.main(ActivityThread.java:5225)
                                                                     at
java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at
java.lang.reflect.Method.invoke(Method.java:525)
                                                                     at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
                                                                     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
                                                                     at
dalvik.system.NativeStart.main(Native Method)

i did more research and found

this class (de.schlichtherle.truezip.fs.archive.zip.ZipDriverService
https://truezip.java.net/apidocs/de/schlichtherle/truezip/fs/archive/zip/ZipDriverService.html
) needed for zip driver mapping and i did't found this class in your lib.

can you please look into this.

see below for more reference
https://truezip.java.net/truezip-driver/truezip-driver-zip/index.html

Thank you.

**Comment by jruesga** [comment]
I'm afraid you cannot use this library at this way. I stripped it down to make sure it runs in Android and with only intention of use the RAES drivers. From the changelog:

> ## TrueZip v7
> 
> Grabbed from https://hg.java.net/hg/truezip~v7 (r6207).
> The source was downgraded to fully comply with JS6 and remove NIO2/ServiceLocator/Swing/Console
> support and stripped down to use the minimal subset of classes to run RAES engine. Removed
> javax/findBugs annotations. This port doesn't contain any driver or keyprovider registered
> as default. Default locators doesn't return any implementation. Implementators should
> define its own set of fsdrivers and keyproviders.

Basically, you can not use TArchiveDetector, because there isn't any want registered. Instead you mus define your own driver. I ported this library just to complain with the needs of CMFileManage. Check out how is done in https://github.com/CyanogenMod/android_packages_apps_CMFileManager/tree/cm-13.0/src/com/cyanogenmod/filemanager/console/secure. There is an implementation of a secure raes filesystem in the SecureStorageDriver, SecureStorageDriverProvider and SecureConsole.

Zip support is still there though, but you must create a singleton instance instead of the detector mechanisms (Android didn't support the ServiceLocator).

**Comment by hardikbhalodi** [comment]
Okay got it, so can you have any example for zip read, write, append,
delete using this lib in android?  I want to use this functionality in
android and In specific, *i want to append zip content *and tried many ways
but no luck. but you saying "Zip support is still there though, but you
must create a singleton instance instead of the detector mechanisms", so if
you have any example for android then please update on git or email will be
great.

Thank you.

**Comment by jruesga** [comment]
https://cloud.ruesga.com/f/5cb2530868/

**Comment by hardikbhalodi** [comment]
I see your example and it will work great. I appreciate your help and work
that you done.

Thank you so much sir for your support.
